Repository OpenTournament/OpenTournament, pull requests merged in 2020-08, with the labels that each got.

#71 Fix #70 projectiles issues
  Binaries/Win64/UE4Editor-OpenTournament.dll
  Source/OpenTournament/UR_Projectile.cpp
  Source/OpenTournament/UR_Projectile.h
Labels: enhancement

#123 OT-#118 : Organize Level File Directories
  Content/OpenTournament/Levels/Experiments/FTEST_ActorTeleporter.umap
  Content/OpenTournament/Levels/Experiments/FTEST_ActorTeleporter_BuiltData.uasset
  Content/OpenTournament/Levels/Experiments/FeaturesLevelActors.umap
  Content/OpenTournament/Levels/Experiments/FeaturesLevelActors_BuiltData.uasset
  Content/OpenTournament/Levels/Experiments/InventoryWeaponTest.umap
  Content/OpenTournament/Levels/Experiments/InventoryWeaponTest_BuiltData.uasset
  Content/OpenTournament/Levels/Experiments/MainMenuScene_Proto1.umap
  Content/OpenTournament/Levels/Experiments/Main_Menu_Scene_Space.umap
  Content/OpenTournament/Levels/Experiments/Test_MovementDimensions.umap
  Content/OpenTournament/Levels/Experiments/Test_MovementDimensions_BuiltData.uasset
  Content/OpenTournament/Levels/Shells/Antenna.umap
  Content/OpenTournament/Levels/Shells/Antenna_BuiltData.uasset
  Content/OpenTournament/Levels/Shells/MoonBase.umap
  Content/OpenTournament/Levels/Shells/MoonBase_BuiltData.uasset
  Content/OpenTournament/Levels/Shells/NukeClear.umap
  Content/OpenTournament/Levels/Shells/NukeClear_BuiltData.uasset
Labels: Production

#126 OT-#118 : Organize Level File Directories
  Content/OpenTournament/Levels/Experiments/FTEST_ActorTeleporter.umap
  Content/OpenTournament/Levels/Experiments/FTEST_ActorTeleporter_BuiltData.uasset
  Content/OpenTournament/Levels/Experiments/FeaturesLevelActors.umap
  Content/OpenTournament/Levels/Experiments/FeaturesLevelActors_BuiltData.uasset
  Content/OpenTournament/Levels/Experiments/InventoryWeaponTest.umap
  Content/OpenTournament/Levels/Experiments/InventoryWeaponTest_BuiltData.uasset
  Content/OpenTournament/Levels/Experiments/MainMenuScene_Proto1.umap
  Content/OpenTournament/Levels/Experiments/Main_Menu_Scene_Space.umap
  Content/OpenTournament/Levels/Experiments/Test_MovementDimensions.umap
  Content/OpenTournament/Levels/Experiments/Test_MovementDimensions_BuiltData.uasset
  Content/OpenTournament/Levels/Shells/Antenna.umap
  Content/OpenTournament/Levels/Shells/Antenna_BuiltData.uasset
  Content/OpenTournament/Levels/Shells/MoonBase.umap
  Content/OpenTournament/Levels/Shells/MoonBase_BuiltData.uasset
  Content/OpenTournament/Levels/Shells/NukeClear.umap
  Content/OpenTournament/Levels/Shells/NukeClear_BuiltData.uasset
Labels: Production

#133 OT-#118 : Organize Level File Directories
  Content/OpenTournament/Levels_Shells/Antenna.umap
  Content/OpenTournament/Levels_Shells/Antenna_BuiltData.uasset
  Content/OpenTournament/Levels_Shells/MoonBase.umap
  Content/OpenTournament/Levels_Shells/MoonBase_BuiltData.uasset
  Content/OpenTournament/Levels_Shells/NukeClear_BuiltData.uasset
Labels: Production

#138 New duel map shell
  Content/OpenTournament/Levels/Shells/Sanctuary.umap
  Content/OpenTournament/Levels/Shells/Sanctuary_BuiltData.uasset
Labels: Blockout, Design, Level
